# SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0
# Copyright (C) 2006-2026 DIY Accounting Limited
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      maven:
        patterns:
          - "*"
